### ISSUE TITLE
GymClass: APIResponse, exists

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.gc.2023.gimnasio.spring#11]
En los controladores incluye el uso de la clase `APIResponse`. Esta, te servirá para inyectar estados del servidor y mensajes de acuerdo a lo que suceda en cada una de las acciones. Puedes ver en mi canal [API Response (Parte 1)](https://youtu.be/kefOBwyBsao) y [API Response (Parte 2)](https://youtu.be/1E8PXQDu7g0). También hay una clase sobre la mejora de controladores [aqui](https://www.youtube.com/watch?v=ttZCHUZkai8)

En el controlador, implementar el método `exists` a nivel del servicio, de acuerdo a la documentación relacionada

Debes realizar las pruebas de todos los métodos del controlador y adjuntar las evidencias.

**Comment by caballeroN** [comment]
![1 - getAll](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/c89fbb8a-9270-4224-b69a-ad166195e7b9)
![2 - getAll-negative](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/f29377c0-2d3a-4251-af4f-07e34c4c8cb0)
![3 - getById](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/aa56ba1d-a9d7-4a0a-903d-90e5bb8ac630)
![4 - getById-negative](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/77a8be29-97f0-4533-936f-ac99a34c0fdc)
![5 - createGymClass](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/aa6351e3-8161-4ddb-90fd-0c21a8be49b4)
![6 - createGymClass-negative](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/ed2e1fa6-0073-4bec-af38-156f68a771aa)
![7- updateGymClass](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/3c32e508-eadf-4229-b848-0ba4f80cfc25)
![8- updateGymClass-negative](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/e1084228-9272-48ed-8a09-24570144934d)
![9 - deleteGymClass](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/648876d5-e774-4c0a-ba45-9fff9f81720b)
![10 - deleteGymClass-negative](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/7731eebc-f7e3-4d26-8eb2-5fa683e0b25b)
