### ISSUE TITLE
MemberShipTransaction, ClassRegistration. Crear estos circuitos. APIResponse, exists

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.gc.2023.gimnasio.spring#12]
En los controladores incluye el uso de la clase `APIResponse`. Esta, te servirá para inyectar estados del servidor y mensajes de acuerdo a lo que suceda en cada una de las acciones. Puedes ver en mi canal [API Response (Parte 1)](https://youtu.be/kefOBwyBsao) y [API Response (Parte 2)](https://youtu.be/1E8PXQDu7g0). También hay una clase sobre la mejora de controladores [aqui](https://www.youtube.com/watch?v=ttZCHUZkai8)

En el controlador, implementar el método `exists` a nivel del servicio, de acuerdo a la documentación relacionada

Debes realizar las pruebas de todos los métodos del controlador y adjuntar las evidencias.

**Comment by Fer-Cod** [comment]
Gracias Profesor, Empiezo a trabajar con esto.
