### ISSUE TITLE
Mejoras en la entidad: GymClass

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.gc.2023.gimnasio.spring#19]
**Entidad**

Verificar que en tu entidad asignada tenga las relaciones `@ManyToOne` correspondientes

**Servicios**

Crear la interfase y la implementación de la interfase similar a lo siguiente:

``` java
public interface IMiEntidadService {

    public List<MiEntidad> buscarTodos();
    public MiEntidad buscarPorId(Integer id);
    public MiEntidad guardar (MetodoDePago metodoDePago);
    public void eliminar(Integer id);
    public boolean existe(Integer id);
}
```

**Controlador**

Crear en el controlador métodos para los siguientes *actions*

  - `GET` para obtener el listado de todos los elementos.
  - `GET` para obtener un solo elemento por *id*.
  - `POST` para la creación de un nuevo elemento.
  - `PUT` para la modificación de un elemento.
  - `DELETE` para la eliminación de un elemento por su id

**Además, se debe tener en cuenta lo siguiente:**

  - *Convención de nombres:* para los nombres de los métodos en el controlador, debes incluir la referencia a su entidad (a diferencia de lo que sucede en el servicio) por ejemplo: buscarPersonaPorId.
  - *Utilidades del response*: utilizar el objeto ResponseEntity combinado con el objeto APIResponse. Utilizar la utilidad ResponseUtil.
  - *Manejo de excepciones*: añadir el manejo de excepciones utilizando la utilidad del ResponseUtil

**Como tarea adicional, se requiere lo siguiente:**

  - Crear una documentación (de código comentado) explicando y detallando lo mejor posible el funcionamiento técnico de la siguiente parte del código:

*En el controlador, documenta con comentarios el método `GET` donde obtienes todos los elementos*

  - Probar todos los métodos del controlador y hacer captura de pantalla de la evidencia obtenida. Esta evidencia debe ser incluida en los comentarios del pull request.

**Recuerda que la primera entrega de la tarea es el 19 de Octubre y la entrega final el 26 de Octubre**

**Comment by caballeroN** [comment]
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/75ace957-9ea9-4257-91b2-fe6134959c43)
 
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/f2b0e219-6970-4392-986b-c19844806de7)

![image](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/0f2eeb3d-d7e6-45f3-86b4-8efb3d1d42c6)

![image](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/b92dd718-5c3a-4150-9939-848c747c8245)

![image](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/aec07fd8-dd3e-4f10-a1d7-85855f09a1bc)

![image](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/bb528253-f6b9-4932-9ee6-b87310c367df)

![image](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/f2e01463-2534-4c19-94d3-2c6bc8fcd6bf)

![image](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/bc48cfcc-8c80-4ced-ab8f-f147b15cf192)

![image](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/e67e8236-e018-461a-915f-e2691bb58323)

![image](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/43214820/acac02ef-96d5-42dc-9ae3-78367cccc6b2)
