### ISSUE TITLE
Mejoras en la entidad: MemberShipTransaction

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.gc.2023.gimnasio.spring#20]
**Entidad**

Verificar que en tu entidad asignada tenga las relaciones `@ManyToOne` correspondientes

**Servicios**

Crear la interfase y la implementación de la interfase similar a lo siguiente:

``` java
public interface IMiEntidadService {

    public List<MiEntidad> buscarTodos();
    public MiEntidad buscarPorId(Integer id);
    public MiEntidad guardar (MetodoDePago metodoDePago);
    public void eliminar(Integer id);
    public boolean existe(Integer id);
}
```

**Controlador**

Crear en el controlador métodos para los siguientes *actions*

  - `GET` para obtener el listado de todos los elementos.
  - `GET` para obtener un solo elemento por *id*.
  - `POST` para la creación de un nuevo elemento.
  - `PUT` para la modificación de un elemento.
  - `DELETE` para la eliminación de un elemento por su id

**Además, se debe tener en cuenta lo siguiente:**

  - *Convención de nombres:* para los nombres de los métodos en el controlador, debes incluir la referencia a su entidad (a diferencia de lo que sucede en el servicio) por ejemplo: buscarPersonaPorId.
  - *Utilidades del response*: utilizar el objeto ResponseEntity combinado con el objeto APIResponse. Utilizar la utilidad ResponseUtil.
  - *Manejo de excepciones*: añadir el manejo de excepciones utilizando la utilidad del ResponseUtil

**Como tarea adicional, se requiere lo siguiente:**

  - Crear una documentación (de código comentado) explicando y detallando lo mejor posible el funcionamiento técnico de la siguiente parte del código:

*En el controlador, documenta con comentarios el método `GET` para obtener un solo elemento por id

  - Probar todos los métodos del controlador y hacer captura de pantalla de la evidencia obtenida. Esta evidencia debe ser incluida en los comentarios del pull request.

**Recuerda que la primera entrega de la tarea es el 19 de Octubre y la entrega final el 26 de Octubre**

**Comment by Fer-Cod** [comment]
Save Entidad MembershipTransaction
![Post - MembershipTransaction Save](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/cefb1c52-9983-4d21-827d-1d1feb79ff1c)

Save Member

![Post - Member Save](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/c3d021fd-c0ff-4c55-8690-8ad68eba8338)

GetAll Entidad MembershipTransaction
![Get- MembershipTransaction GetAll](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/8124dfb2-27a9-46ab-8a24-c2302250a6e9)

GetAll Member
![GET- Member GetAll](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/deba04a6-e30e-4401-8c74-474f60ade645)

GetOne Entidad MembershipTransaction
![Get- MembershipTransaction GetOne](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/414c0ff2-bdf9-46c3-8bc5-d7dfe6761a24)

GetOne Member
![GET- Member GetOne](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/6111128e-a9b9-4a4c-bb1a-c602eb796244)

PUT Entidad MembershipTransaction Edit
![Put- MembershipTransaction Edit](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/97f930c6-35a1-4d9d-8887-d976283a4f7e)

PUT Member Edit
![PUT- Member Edit](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/9e310d11-dd56-4696-b7aa-d6b1a764af1d)

DELETE Member
![Delete- Member delete](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/7b61ee4c-53c8-4d53-859e-9b3883a189ec)
