### ISSUE TITLE
Nuevos endpoints para la entidad MemberShip

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.gc.2023.gimnasio.spring#26]
1. Agrega un nuevo atributo a la entidad MemberShipTransaction llamado `enabled`. Debe ser un atributo del tipo `boolean` en el cual `true` significa que estará habilitado y `false` deshabilitado.
2. Crea un nuevo endpoint para habilitar un MemberShip y otro endpoint para deshabilitar un MemberShip.
3. Crea un endpoint para listar los MemberShip habilitados y otro endpoint para listar los MemberShip deshabilitados.
4. Crea un endpoint para eliminar un MemberShip siempre y cuando esté deshabilitado.
5. Realiza las capturas de pantalla de todos estos nuevos endpoints utilizando PostMan

**Comment by Fer-Cod** [comment]
End Point Get All
![GET - MembershipTransaction getAll](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/ed23ee6b-19e6-422d-be67-311fb24c3ebe)

End Point Get All Enable
![GET - MembershipTransaction getEnable](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/a6ac5183-8203-461c-8789-bb96e65b5e06)

End Point Get All Disable
![GET - MembershipTransaction getDisable](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/188cd564-3ce9-4458-8807-10eadd7eebcd)

End Point Get Enable Id
![GET - MembershipTransaction getEnable Id](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/3434f2be-fe52-4fcb-be42-e034f324e2cf)

End Point Put Enable to Disable
![PUT- MembershipTransaction Disable Id](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/cead8ece-ae6a-43bd-919c-268c6ed91556)

End Point Delete Disable
![DELETE- MembershipTransaction Delete Disable Id](https://github.com/ahumadamob/imb.pr3.gc.2023.gimnasio.spring/assets/92583709/99bc933d-ef53-47e1-9feb-aefdcaa576fc)
